[App] enh: shellcheck it baby

diff --git a/openmole/bin/openmole-naked/src/main/resources/openmole b/openmole/bin/openmole-naked/src/main/resources/openmole
--- a/openmole/bin/openmole-naked/src/main/resources/openmole
+++ b/openmole/bin/openmole-naked/src/main/resources/openmole
@@ -1,51 +1,54 @@
 #!/bin/bash
 
+function cd_or_die() {
+  cd "$1" || (echo "Can't cd to $1" >&2; exit 3)
+}
+
 # Limit virtual memory on docker
 export MALLOC_ARENA_MAX=4
 
-CURDIR=$PWD
+CURDIR="${PWD}"
 
-#REALPATH=`readlink -f $0`
-#LOCATION=`dirname "$REALPATH"`
+#REALPATH=$(readlink -f $0)
+#LOCATION=$(dirname "$REALPATH")
 
 #readlink -f does not work on mac, use alternate script
 TARGET_FILE=$0
 
-cd `dirname $TARGET_FILE`
-TARGET_FILE=`basename $TARGET_FILE`
+cd_or_die "$(dirname "${TARGET_FILE}")"
+TARGET_FILE="$(basename "${TARGET_FILE}")"
 
 # Iterate down a (possible) chain of symlinks
-while [ -L "$TARGET_FILE" ]
+while [ -L "${TARGET_FILE}" ]
 do
-    TARGET_FILE=`readlink $TARGET_FILE`
-    cd `dirname $TARGET_FILE`
-    TARGET_FILE=`basename $TARGET_FILE`
+    TARGET_FILE="$(readlink "${TARGET_FILE}")"
+    cd_or_die "$(dirname "${TARGET_FILE}")"
+    TARGET_FILE="$(basename "${TARGET_FILE}")"
 done
 
 REALPATH=$TARGET_FILE
 #end of readlink -f
 
-LOCATION=$( cd $(dirname $REALPATH) ; pwd -P )
-cd "$CURDIR"
+LOCATION=$( cd_or_die "$(dirname "${REALPATH}")" ; pwd -P )
+cd_or_die "$CURDIR"
 
 MEM=${OPENMOLE_MEMORY:-"2G"}
 # enable through command line arguments --debug and --debug-port
 DEBUG_MODE=false
 DEBUG_PORT=5005
-DEBUG_FLAGS=""
-FLAG=""
+FLAGS=()
 
-JAVAVERSION=`java -version 2>&1`
+JAVAVERSION=$(java -version 2>&1)
 
-JVMFLAVOR=`echo "$JAVAVERSION" | tail -1`
+JVMFLAVOR=$(echo "$JAVAVERSION" | tail -1)
 case "$JVMFLAVOR" in
-  *64-Bit*) FLAG="-XX:+UseCompressedOops";;
+  *64-Bit*) FLAGS+=("-XX:+UseCompressedOops");;
 esac
 
-JVMVERSION=`echo "$JAVAVERSION" | grep version | rev | cut -d' ' -f1 | rev`
+JVMVERSION=$(echo "$JAVAVERSION" | grep version | rev | cut -d' ' -f1 | rev)
 case "$JVMVERSION" in
   *1\.6\.*) echo "Your java version is too old"; exit 1;;
-  *1\.7\.*) FLAG="$FLAG -XX:MaxPermSize=128M";;
+  *1\.7\.*) FLAGS+=("-XX:MaxPermSize=128M");;
 esac
 
 ARGS=()
@@ -89,17 +92,17 @@ done
 shift $((OPTIND-1)) # remove parsed options and args from $@ list
 
 if [ ${DEBUG_MODE} == true ]; then
-  DEBUG_FLAGS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=${DEBUG_PORT}"
+  FLAGS+=("-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=${DEBUG_PORT}")
 fi
 
 # Try to increase the max number of opened files
-if [[ `ulimit -S -n` < 4096 ]]; then ulimit -S -n 4096 2>/dev/null; fi
+if [[ $(ulimit -S -n) -lt 4096 ]]; then ulimit -S -n 4096 2>/dev/null; fi
 
 function run {
   mkdir -p "$HOME/.openmole/.tmp/"
-  CONFIGDIR=$HOME/.openmole/.tmp/`date +%s`_$RANDOM
+  CONFIGDIR=$HOME/.openmole/.tmp/$(date +%s)_$RANDOM
 
-  java ${DEBUG_FLAGS} -Xss2M -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom -Dosgi.locking=none -Dopenmole.location="${LOCATION}" -Dosgi.classloader.singleThreadLoads=true  -Dosgi.configuration.area="${CONFIGDIR}" -Xmx${MEM} $FLAG \
+  java -Xss2M -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom -Dosgi.locking=none -Dopenmole.location="${LOCATION}" -Dosgi.classloader.singleThreadLoads=true  -Dosgi.configuration.area="${CONFIGDIR}" "-Xmx${MEM}" "${FLAGS[@]}" \
      -XX:+UseG1GC -XX:CICompilerCount=2 -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:G1ConcRefinementThreads=2 \
      -cp "${LOCATION}/launcher/*" org.openmole.launcher.Launcher  --plugins "${LOCATION}/plugins/" --priority "logging" --run org.openmole.ui.Application --osgi-directory "${CONFIGDIR}" -- \
      "${ARGS[@]}" "${SCRIPT_ARGS[@]}"
