[App] enh: switch to getopts for command line arg management

diff --git a/openmole/bin/openmole-naked/src/main/resources/openmole b/openmole/bin/openmole-naked/src/main/resources/openmole
--- a/openmole/bin/openmole-naked/src/main/resources/openmole
+++ b/openmole/bin/openmole-naked/src/main/resources/openmole
@@ -49,19 +49,44 @@ case "$JVMVERSION" in
 esac
 
 ARGS=()
-while [[ $# -gt 0 ]]; do
-  case "$1" in
-    --) ARGS+=("$@"); break ;;
-    --mem) shift; MEM=$1 ;;
-    --workspace) ARGS+=("$1"); shift; WORKSPACE=$1; ARGS+=("$1");;
-    --debug) DEBUG_MODE=true;;
-    --debug-port) shift; DEBUG_PORT="$1";;
-    *) ARGS+=("$1") ;;
-  esac
-  shift
-done
-
 SCRIPT_ARGS=()
+
+function usage() {
+cat <<EOF
+Usage: $0 <[options]>
+Options:
+  -d   --debug          Enable remote debugging (for developers)
+  -h   --help           Show this message
+  -m   --mem=           Set OpenMOLE application's memory (default: --mem=${MEM})
+  -p   --debug-port=    Set port for remote debugging (default: --debug-port=${DEBUG_PORT})
+  -w   --workspace=     Set OpenMOLE application's workspace (default: --workspace=${HOME}/.openmole/$(hostname))
+EOF
+exit 0
+}
+
+# from http://stackoverflow.com/a/28466267/470341
+while getopts dhm:w:p:-: arg; do
+  case "${arg}" in
+    d )  DEBUG_MODE=true ;;
+    h )  usage ;;
+    m )  MEM="${OPTARG}" ;;
+    p )  DEBUG_PORT="${OPTARG}" ;;
+    w )  WORKSPACE="${OPTARG}"; ARGS+=("--workspace"); ARGS+=("${WORKSPACE}") ;;
+    - )  LONG_OPTARG="${OPTARG#*=}"
+      case ${OPTARG} in
+        debug    )    DEBUG_MODE=true ;;
+        help     )    usage ;;
+        mem=?*   )    MEM="${LONG_OPTARG}" ;;
+        debug-port=?* )    DEBUG_PORT="${LONG_OPTARG}" ;;
+        workspace=?*  )    WORKSPACE="${LONG_OPTARG}"; ARGS+=("--workspace"); ARGS+=("${WORKSPACE}") ;;
+        usage | debug*   )    echo "No arg allowed for --${OPTARG} option" >&2; exit 2 ;;
+        mem* | debug-port* | workspace*    )    echo "Missing arg for --${OPTARG} option" >&2; exit 2 ;;
+        '' | * )        ARGS+=("$@"); break ;; # "--" terminates argument processing
+      esac ;;
+    * ) ARGS+=("${OPTARG}");;
+  esac
+done
+shift $((OPTIND-1)) # remove parsed options and args from $@ list
 
 if [ ${DEBUG_MODE} == true ]; then
   DEBUG_FLAGS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=${DEBUG_PORT}"
